# Generated by Django 6.0.6 on 2026-06-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_chapter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
